#!/usr/bin/env python3
"""board — the roadmap is one file per item; ROADMAP.md is its generated index.

WHY THE BOARD SPLIT (ADR 2026-08-15, Mike's ruling)
----------------------------------------------------
One 4,000-line ROADMAP.md was simultaneously the unit of contention (every
session edits it, and a wholesale revert destroyed a sibling session's in-flight
work), the unit of reading (~67k tokens at every session open), and the unit of
truth for a hundred-plus independent items whose "done" was asserted in prose
and drifted from the tree five recorded times. Splitting the store to one file
per item under `docs/roadmap/` fixes all three at the grain where they occur:
two sessions on different items now touch different files; the session-start
read is a short index; and an item's own `git log` is its provenance — which
commit flipped its state, and what work that commit carried.

THE LAYOUT THIS TOOL OWNS
--------------------------
    docs/roadmap/README.md              board preamble (checkbox legend etc.)
    docs/roadmap/<NN>-<section>/README.md   section narrative, verbatim
    docs/roadmap/<NN>-<section>/<NN>-<slug>.md  ONE item: its checkbox line
                                          first, continuations beneath
    docs/ROADMAP.md                     GENERATED index — never hand-edited

Item files keep the board's existing checkbox grammar VERBATIM — `- [ ]` open,
`- [~] (claimed …)`, `- [x]` done, `- ⏳` a queued-review pointer — because
every scanner that reads items (`harvestscan`, `pointerscan`, `sizescan`)
already speaks that grammar, and a second state vocabulary (frontmatter) would
be one fact in two homes. State lives in the item file's first line and nowhere
else; the index derives from it.

WHY THE INDEX IS COMMITTED AND CHECKED, NOT HAND-KEPT
------------------------------------------------------
A committed derived file can drift from its source — the estate's most-recorded
defect class. So this tool is wired into the floor as a CHECK: a commit whose
index does not match its item files fails, with the remedy printed (run
`rebuild`). Two sessions closing different items both regenerate; if their
index hunks collide, the resolution is deterministic — regenerate again after
the merge. The index renders done items as `✅`, never `[x]`, so `sizescan`'s
cold-content gate (a `[x]` on the hot path) can never fire on a generated line.

The index opens with a GENERATED marker line. Scanners that lint *item* grammar
(`pointerscan`) skip any file carrying it — the index's one-line renderings are
projections, not the items themselves.

CHILD REPOS. A repo with no `docs/roadmap/` directory is not using the split
board; the check reports not-in-scope and exits 0. That is the same graceful
posture every scoped scanner takes, and it is not fail-open: the check's
subject (a generated index) does not exist where the store does not.

WHAT THE GENERATOR MAY NOT ASSUME (learned from the first child, 2026-08-17).
This tool writes text that is READ somewhere it was never written for, so
every string it emits into a committed file must be true in a repo that is
not this one. Two ways that failed at once when `faves` adopted the board:
the banner named `tools/board.py`, which exists only where the tool lives —
children CALL the floor's tools and never vendor them (ADR 0008) — and the
section links repeated their own path as the link TEXT, which `pathscan`
resolves, so a clean child produced one false finding per section on every
commit. Hence `rebuild_cmd()`: repo-relative where the tool is inside the
tree, the hook's `$ATELIER_TOOLS` spelling where it is not, and NEVER an
absolute path, which would put a machine-local fact into a public file.

STATED RESIDUAL. `--check` compares the WORKTREE's item files against the
WORKTREE's index. A commit staging an item edit but not the rebuilt index is
caught only because the hook runs after `git add` of both or neither in
practice; the staged-vs-worktree seam (`HV4`'s INDEX-source discipline in
harvestscan) is not yet implemented here. Queued as a follow-up on the board.

Exit codes:  0 clean/not-in-scope · 1 stale index or invalid item file ·
2 environment error (bad root). `--selftest` proves the core offline.
"""

from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from pathlib import Path

BOARD_DIR = "docs/roadmap"
INDEX_REL = "docs/ROADMAP.md"

# The marker is matched as a PREFIX, and the legacy spelling is still accepted
# so no repo needs a flag day: an index generated before 2026-08-17 keeps its
# skip in pointerscan until its next rebuild, which the check demands anyway.
GENERATED_MARK = "<!-- GENERATED by board.py"
GENERATED_MARKS = (GENERATED_MARK, "<!-- GENERATED by tools/board.py")

# The banner names NO path. It used to say `python3 tools/board.py rebuild`,
# which is true only in the repo the tool lives in — children call the floor's
# tools and never vendor them (ADR 0008), so in every child the one instruction
# printed at the top of the one file readers are told never to hand-edit named
# a file that was not there. The HOW moved to the preamble, which is built
# against a known root and can therefore be true from where the reader stands.
GENERATED_LINE = (
    "<!-- GENERATED by board.py — do not hand-edit; edit docs/roadmap/ -->"
)

# The board's item grammar — the SAME shape harvestscan/pointerscan read, but
# anchored to column 0: an item file's state line is top-level by definition,
# and an indented match is a sub-bullet of the item, not a second item.
STATE_RE = re.compile(r"^-\s+(\[[ x~]\]|⏳)\s*(.*)$")

# Eye-flags lifted from the state line into the index, in the order shown.
FLAGS = ("🎯", "🔥", "🛑", "⏳", "🔎", "🤔")

# A claim fragment, surfaced in the index so "who has this" is one glance.
CLAIM_RE = re.compile(r"\(claimed [^)]*\)")

TITLE_RE = re.compile(r"\*\*(.+?)\*\*")
LINK_RE = re.compile(r"\[([^\]]*)\]\([^)]*\)")
TITLE_MAX = 70

# Allow-markers on the source state line travel to the generated line: the
# projection reproduces the exempted text (a verbatim title can carry a
# non-ISO date), so it inherits the exemption — found live on day one, when
# the index re-flagged a date its item file had already scoped-allowed.
ALLOW_COMMENT_RE = re.compile(r"<!--[^>]*\ballow\b[^>]*-->")


def slug(text: str, limit: int = 46) -> str:
    """Filesystem-safe kebab slug, the session-file convention."""
    text = unicodedata.normalize("NFKD", text)
    text = "".join(c for c in text if not unicodedata.combining(c))
    text = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    return text[:limit].rstrip("-") or "item"


def item_state(text: str) -> tuple[str, str] | None:
    """(marker, rest-of-line) from an item file's first item line, else None.

    Leading HTML comments and blank lines are tolerated — an item file may open
    with an allow-marker — but prose before the state line is a defect the
    check reports: state must be findable without reading the body.
    """
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("<!--"):
            continue
        m = STATE_RE.match(line)
        return (m.group(1), m.group(2)) if m else None
    return None


def index_title(rest: str) -> str:
    """The index line's link text: the item's bold title, links flattened."""
    m = TITLE_RE.search(rest)
    raw = m.group(1) if m else rest
    raw = LINK_RE.sub(r"\1", raw)
    raw = raw.replace("*", "").replace("`", "").strip(" —-:")
    for f in FLAGS:
        raw = raw.replace(f, "")
    raw = " ".join(raw.split())
    if len(raw) > TITLE_MAX:
        raw = raw[:TITLE_MAX].rsplit(" ", 1)[0] + "…"
    return raw or "(untitled)"


def index_line(marker: str, rest: str, rel_link: str) -> str:
    """One generated index line for an item. `[x]` renders ✅ by design."""
    glyph = {"[ ]": "- [ ]", "[~]": "- [~]", "[x]": "- ✅", "⏳": "- ⏳"}[marker]
    flags = "".join(f for f in FLAGS if f in rest and f != marker)
    title = index_title(rest)

    # Flags and the claim fragment go BEFORE the link, and the reason is
    # mechanical, not taste. wrapscan exempts a line whose overflow is one
    # unbreakable token — which every item line is, because it ends in a
    # store path. Appending ` 🎯` put a space *after* that path, so the
    # overflow gained a legal wrap point and the exemption stopped applying:
    # in the first child, 13 of the index's 14 wrapscan findings were exactly
    # its 13 flagged lines, and nothing else. Leading them costs nothing, and
    # a reader gains a flag column that aligns instead of tracking flags to
    # ragged line ends. Allow-comments stay last — a trailing marker is how
    # every scanner reads them, and a line carrying one exempts itself anyway.
    line = glyph
    if flags:
        line += f" {flags}"
    if marker == "[~]":
        m = CLAIM_RE.search(rest)
        if m:
            line += f" {m.group(0)}"
    line += f" [{title}]({rel_link})"
    for c in ALLOW_COMMENT_RE.findall(rest):
        line += f" {c}"
    return line


def section_title(readme_text: str, fallback: str) -> str:
    for line in readme_text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def rebuild_cmd(root: Path) -> str:
    """The rebuild instruction, true from where the reader stands.

    In atelier the tool lives inside the tree it rebuilds, so the repo-relative
    path is both true and copy-pasteable. In a child it does not live there —
    and an absolute path must never be written into a committed file, because
    it is a machine-local fact in a tree that may be public. So a child gets
    the hook's own resolution variable, which is the one spelling that is true
    everywhere and names nobody's home directory.
    """
    try:
        here = Path(__file__).resolve().relative_to(root.resolve())
    except ValueError:
        return 'python3 "$ATELIER_TOOLS"/board.py rebuild'
    return f"python3 {here.as_posix()} rebuild"


def build_index(board: Path) -> tuple[str, list[str]]:
    """(index text, problems). Deterministic: sorted dirs, sorted files."""
    problems: list[str] = []
    parts: list[str] = [GENERATED_LINE, ""]
    cmd = rebuild_cmd(board.parent.parent)

    # The preamble is LINKED, never inlined: its relative links are written
    # for its own home (docs/roadmap/), and inlining the text at the index's
    # depth would break every one of them — one text cannot be correct at two
    # depths. The index carries only what it generates.
    parts.append("# ROADMAP — board index")
    parts.append("")
    if (board / "README.md").is_file():
        # Wrapped by hand at the house width: it is the index's one line of
        # real prose, and the only finding left once the flags moved.
        parts.append("Board doctrine and the checkbox legend:")
        parts.append("[roadmap/README.md](roadmap/README.md). One item per "
                     "file; edit the item,")
        parts.append(f"then `{cmd}`.")
        parts.append("")
    else:
        problems.append(f"{BOARD_DIR}/README.md missing — the board preamble "
                        "(checkbox legend) has no home")

    for sec in sorted(p for p in board.iterdir() if p.is_dir()):
        readme = sec / "README.md"
        rtext = readme.read_text(encoding="utf-8") if readme.is_file() else ""
        parts.append(f"## {section_title(rtext, sec.name)}")
        parts.append("")
        if readme.is_file():
            # Link TEXT, not just the target: the old text repeated the path,
            # and pathscan resolves both halves of a link, so every section
            # produced one finding per commit in any repo that scans the index
            # (49 in the first child to adopt). A generated file that always
            # fires a warn-only check is a check nobody reads.
            parts.append(f"*[Narrative](roadmap/{sec.name}/README.md)*")
            parts.append("")
        wrote = False
        for f in sorted(sec.glob("*.md")):
            if f.name == "README.md":
                continue
            state = item_state(f.read_text(encoding="utf-8"))
            if state is None:
                problems.append(
                    f"{BOARD_DIR}/{sec.name}/{f.name}: no state line — an item "
                    "file opens with its checkbox line (`- [ ] …`), before any "
                    "prose")
                continue
            marker, rest = state
            parts.append(index_line(marker, rest,
                                    f"roadmap/{sec.name}/{f.name}"))
            wrote = True
        if wrote:
            parts.append("")
    text = "\n".join(parts).rstrip() + "\n"
    return text, problems


def run_check(root: Path, fix: bool) -> int:
    board = root / BOARD_DIR
    if not board.is_dir():
        print(f"✓ board not in scope — no {BOARD_DIR}/ directory "
              "(this repo does not use the split board).")
        return 0
    want, problems = build_index(board)
    for p in problems:
        print(f"✗ board: {p}")
    index = root / INDEX_REL
    have = index.read_text(encoding="utf-8") if index.is_file() else ""
    if fix:
        if have != want:
            index.write_text(want, encoding="utf-8")
            print(f"✓ board: {INDEX_REL} rebuilt "
                  f"({len(want.splitlines())} lines).")
        else:
            print(f"✓ board: {INDEX_REL} already current.")
        return 1 if problems else 0
    if have != want:
        print(f"✗ board: {INDEX_REL} is stale against {BOARD_DIR}/ — "
              f"run: {rebuild_cmd(root)}   (then stage the index; "
              "after a merge conflict on the index, rebuilding IS the "
              "resolution)")
        return 1
    if not problems:
        print(f"✓ board index current — {INDEX_REL} matches {BOARD_DIR}/.")
    return 1 if problems else 0


# ---------------------------------------------------------------------------
def selftest() -> int:
    import tempfile

    failures: list[str] = []

    def check(name: str, cond: bool) -> None:
        if not cond:
            failures.append(name)

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        sec = root / BOARD_DIR / "10-track-a"
        sec.mkdir(parents=True)
        (root / BOARD_DIR / "README.md").write_text(
            "# board\n\nlegend here\n", encoding="utf-8")
        (sec / "README.md").write_text("# Track A — live exposure\nwhy\n",
                                       encoding="utf-8")
        (sec / "10-fix-the-gate.md").write_text(
            "- [ ] 🎯 **Fix the gate** — the gate fails open\n      detail\n",
            encoding="utf-8")
        (sec / "20-done-thing.md").write_text(
            "- [x] **Shipped thing** — landed\n", encoding="utf-8")
        (sec / "30-claimed.md").write_text(
            "- [~] **Mid-flight** … (claimed 2026-08-15-0610, wt: b) more\n",
            encoding="utf-8")
        (sec / "40-pointer.md").write_text(
            "- ⏳ Rule-4 review queued — delta abc..def\n", encoding="utf-8")
        (sec / "50-marked.md").write_text(
            "- [ ] **Verbatim (15/7/26) title** "
            "<!-- datescan:allow: verbatim --> — body\n", encoding="utf-8")

        # not-in-scope: a bare tree passes without a board directory
        with tempfile.TemporaryDirectory() as bare:
            check("bare tree exits 0", run_check(Path(bare), fix=False) == 0)

        # a missing index is stale; rebuild writes it; then check passes
        check("missing index is stale", run_check(root, fix=False) == 1)
        check("rebuild exits 0", run_check(root, fix=True) == 0)
        check("rebuilt index passes", run_check(root, fix=False) == 0)

        text = (root / INDEX_REL).read_text(encoding="utf-8")
        check("generated marker first",
              text.splitlines()[0].startswith(GENERATED_MARK))
        check("banner names no path", "tools/board.py" not in
              text.splitlines()[0] and "$ATELIER_TOOLS" not in
              text.splitlines()[0])
        check("narrative link text is not path-shaped",
              "*[Narrative](roadmap/" in text
              and "*Narrative: [" not in text)
        # The selftest root is a tempdir, so this file is OUTSIDE it — which
        # is exactly a child's geometry, and the reason the child spelling is
        # the one the offline test proves.
        check("child root gets the portable rebuild command",
              '`python3 "$ATELIER_TOOLS"/board.py rebuild`' in text)
        check("no home directory in the index", str(Path.home()) not in text)
        check("open item rendered", "[Fix the gate]" in text)
        check("flag lifted", "🎯" in text)
        # The wrapscan exemption depends on the line ENDING in its path, so
        # the flag leading the link is load-bearing, not cosmetic.
        check("flag precedes the link", "- [ ] 🎯 [Fix the gate](" in text)
        check("no item line ends in a flag",
              not any(line.rstrip().endswith(FLAGS)
                      for line in text.splitlines()
                      if line.startswith("- ")))
        check("done renders ✅ never [x]",
              "- ✅ [Shipped thing]" in text and "- [x]" not in text)
        check("claim fragment surfaced",
              "(claimed 2026-08-15-0610, wt: b)" in text)
        check("pointer glyph kept", "- ⏳ [" in text)
        check("allow-marker travels to the generated line",
              "<!-- datescan:allow: verbatim -->" in text)
        check("section heading from README", "## Track A — live exposure" in text)
        check("preamble linked, never inlined",
              "(roadmap/README.md)" in text and "legend here" not in text)

        # editing an item makes the committed index stale again
        (sec / "10-fix-the-gate.md").write_text(
            "- [x] 🎯 **Fix the gate** — the gate fails open (done)\n",
            encoding="utf-8")
        check("state flip detected", run_check(root, fix=False) == 1)
        run_check(root, fix=True)

        # an item file with no state line is a reported defect
        (sec / "50-broken.md").write_text("just prose\n", encoding="utf-8")
        check("stateless item file fails", run_check(root, fix=True) == 1)
        (sec / "50-broken.md").unlink()
        run_check(root, fix=True)

        # determinism: rebuild twice, byte-identical
        a = (root / INDEX_REL).read_text(encoding="utf-8")
        run_check(root, fix=True)
        b = (root / INDEX_REL).read_text(encoding="utf-8")
        check("rebuild is deterministic", a == b)

        # THE FLOOR'S OWN ARGV must run, not abort the process. This is the
        # exact shape floor.py renders (`{scope}` after `--root`); it exited 2
        # on every repo until parse_known_args replaced parse_args.
        check("floor argv runs",
              main(["check", "--root", str(root), str(root)]) == 0)
        check("floor argv reaches the action",
              main(["rebuild", "--root", str(root), str(root)]) == 0)
        try:
            rc = main(["check", "--root", str(root), "--bogus"])
        except SystemExit as e:
            rc = e.code
        check("an unknown option is still an error", rc == 2)

    if failures:
        print("board selftest FAIL: " + "; ".join(failures))
        return 1
    print("board selftest OK")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="check (default) or rebuild the generated roadmap index")
    ap.add_argument("action", nargs="?", default="check",
                    choices=["check", "rebuild"])
    ap.add_argument("--root", default=".")
    ap.add_argument("paths", nargs="*",
                    help="accepted for floor argv compatibility; the board "
                         "location is fixed at docs/roadmap/")
    ap.add_argument("--selftest", action="store_true")
    # THE FLOOR RENDERS `check --root <root> <scope>`, and argparse cannot bind
    # positionals that an intervening optional has split into two runs (a known
    # argparse limitation, not a template bug): `check` binds, `<scope>` lands
    # in the leftovers and `parse_args` aborts the process with exit 2. That is
    # what `paths` was added to absorb, and it never could. The consequence was
    # not cosmetic — `board` is enforced with no advisory form, so every repo
    # the floor invoked it in went red on an argv it had itself rendered, and
    # the estate could not commit. Unknown OPTIONS stay an error; unknown
    # positionals are the scope this tool has always ignored, because the board
    # location is fixed at docs/roadmap/.
    args, extra = ap.parse_known_args(argv)
    unknown_opts = [a for a in extra if a.startswith("-")]
    if unknown_opts:
        ap.error("unrecognized arguments: " + " ".join(unknown_opts))
    if args.selftest:
        return selftest()
    root = Path(args.root)
    if not root.is_dir():
        print(f"✗ board: root {args.root} does not exist", file=sys.stderr)
        return 2
    return run_check(root, fix=(args.action == "rebuild"))


if __name__ == "__main__":
    sys.exit(main())
